<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * OrdersTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersTotalRepository extends \Doctrine\ORM\EntityRepository
{
}
