<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * OrdersItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersItemRepository extends \Doctrine\ORM\EntityRepository
{
}
