<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * OrdersPaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersPaymentsRepository extends \Doctrine\ORM\EntityRepository
{
}
