<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * OrdersTaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersTaxRepository extends \Doctrine\ORM\EntityRepository
{
}
