inamika_frontend_account:
    path:     /
    defaults: { _controller: InamikaFrontendBundle:Account:index }
    options:
        breadcrumb:
            label: Mi Datos
inamika_frontend_account_orders:
    path:     /MisCompras
    defaults: { _controller: InamikaFrontendBundle:Account:orders }
    options:
        breadcrumb:
            label: Mis compras
inamika_frontend_account_order:
    path:     /MisCompras/{id}
    defaults: { _controller: InamikaFrontendBundle:Account:order }
    options:
        breadcrumb:
            label: Mis compras
inamika_frontend_account_convenios:
    path:     /ContratosActivos/GestionResiduos
    defaults: { _controller: InamikaFrontendBundle:Account:convenios }
    options:
        breadcrumb:
            label: Mis convenios
inamika_frontend_account_convenio:
    path:     /ContratosActivos/GestionResiduos/{id}
    defaults: { _controller: InamikaFrontendBundle:Account:convenio }
    options:
        breadcrumb:
            label: Mis convenios
inamika_frontend_account_contratos:
    path:     /ContratosActivos/UnidadesSanitarias
    defaults: { _controller: InamikaFrontendBundle:Account:contratos }
    options:
        breadcrumb:
            label: Mis contratos
inamika_frontend_account_contrato:
    path:     /ContratosActivos/UnidadesSanitarias/{id}
    defaults: { _controller: InamikaFrontendBundle:Account:contrato }
    options:
        breadcrumb:
            label: Mis contratos
inamika_frontend_account_facturas:
    path:     /MisFacturas
    defaults: { _controller: InamikaFrontendBundle:Account:facturas }
    options:
        breadcrumb:
            label: Mis contratos
inamika_frontend_account_usuarios:
    path:     /Usuarios
    defaults: { _controller: InamikaFrontendBundle:Account:usuarios }
    options:
        breadcrumb:
            label: Mis usuarios
inamika_frontend_account_profile:
    path:     /MisDatos
    defaults: { _controller: InamikaFrontendBundle:Account:profile }
    options:
        breadcrumb:
            label: Mis datos
