inamika_frontend_homepage:
    path:     /
    defaults: { _controller: InamikaFrontendBundle:Default:index }
    options:
        breadcrumb:
            label: Inicio
inamika_frontend_service:
    path:     /Servicio/{section}/{id}
    defaults: { _controller: InamikaFrontendBundle:Default:service }
    options:
        breadcrumb:
            label: Servicio
inamika_frontend_model:
    path:     /Modelo/{section}/{id}
    defaults: { _controller: InamikaFrontendBundle:Default:model }
    options:
        breadcrumb:
            label: Servicio
            
inamika_frontend_cotization:
    path:     /SolicitarCotizacion/{section}/{modelId}
    defaults: { _controller: InamikaFrontendBundle:Default:cotization }
    options:
        breadcrumb:
            label: Solicitar Cotizacion

inamika_frontend_products:
    path:     /Productos
    defaults: { _controller: InamikaFrontendBundle:Default:products }
    options:
        breadcrumb:
            label: Productos

inamika_frontend_salients:
    path:     /Destacados
    defaults: { _controller: InamikaFrontendBundle:Default:salients }
    options:
        breadcrumb:
            label: Productos destacados

inamika_frontend_product:
    path:     /Producto/{id}
    defaults: { _controller: InamikaFrontendBundle:Default:product }
    options:
        breadcrumb:
            label: Producto

inamika_frontend_cart:
    path:     /Carrito
    defaults: { _controller: InamikaFrontendBundle:Default:cart }
    options:
        breadcrumb:
            label: Carrito
inamika_frontend_login:
    path:     /Login
    defaults: { _controller: InamikaFrontendBundle:Login:login }
    options:
        breadcrumb:
            label: Login

inamika_frontend_logout:
    path:     /Logout
    defaults: { _controller: InamikaFrontendBundle:Login:logout }
    options:
        breadcrumb:
            label: Login

inamika_frontend_forgot:
    path:     /OlvideMiContrasena
    defaults: { _controller: InamikaFrontendBundle:Login:forgot }
    options:
        breadcrumb:
            label: Olvide Mi Contrasena

inamika_frontend_resetPassword:
    path:     /BlanquearContrasena/{id}/{code}
    defaults: { _controller: InamikaFrontendBundle:Login:reset }
    options:
        breadcrumb:
            label: Blanquear Contrasena

inamika_frontend_customer_validate:
    path:     /ValidarCuenta/{id}/{code}
    defaults: { _controller: InamikaFrontendBundle:Login:validate }
    options:
        breadcrumb:
            label: Validar Cuenta

inamika_frontend_account:
    resource: "@InamikaFrontendBundle/Resources/config/account.yml"
    prefix:   /MiCuenta