inamika_backoffice_customers:
    path:     /
    defaults: 
        _controller: InamikaBackOfficeBundle:Customers:index
    methods: [GET]
    options:
        breadcrumb:
            label: CUSTOMERS
            parent_route: inamika_backoffice_homepage
            
inamika_backoffice_customers_add:
    path:     /new
    defaults: { _controller: InamikaBackOfficeBundle:Customers:add }
    options:
        breadcrumb:
            label: Agregar cliente
            parent_route: inamika_backoffice_customers
    methods: [GET]

inamika_backoffice_customers_landing:
    path:     /landing/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Customers:landing }
    methods: [GET]
    options:
        breadcrumb:
            label: Demo
            parent_route: inamika_backoffice_customers

inamika_backoffice_customers_import:
    path:     /import
    defaults: { _controller: InamikaBackOfficeBundle:Customers:import }
    methods: [GET]
    options:
        breadcrumb:
            label: Importar cliente
            parent_route: inamika_backoffice_customers

inamika_backoffice_customers_get:
    path:     /get/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Customers:get }
    methods: [GET]
    options:
        breadcrumb:
            label: Demo
            parent_route: inamika_backoffice_customers

inamika_backoffice_customers_edit:
    path:     /edit/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Customers:edit }
    methods: [GET]
    options:
        breadcrumb:
            label: Editar cliente
            parent_route: inamika_backoffice_customers

inamika_backoffice_customers_delete:
    path:     /delete/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Customers:delete }
    methods: [POST,DELETE]