inamika_backoffice_products:
    path:     /
    defaults: 
        _controller: InamikaBackOfficeBundle:Products:index
    methods: [GET]
    options:
        breadcrumb:
            label: PRODUCTS
            parent_route: inamika_backoffice_homepage
            
inamika_backoffice_products_add:
    path:     /new
    defaults: { _controller: InamikaBackOfficeBundle:Products:add }
    options:
        breadcrumb:
            label: PRODUCTS_ADD
            parent_route: inamika_backoffice_products
    methods: [GET]

inamika_backoffice_products_landing:
    path:     /landing/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Products:landing }
    methods: [GET]
    options:
        breadcrumb:
            label: PRODUCT
            parent_route: inamika_backoffice_products

inamika_backoffice_products_import:
    path:     /import
    defaults: { _controller: InamikaBackOfficeBundle:Customers:import }
    methods: [GET]
    options:
        breadcrumb:
            label: PRODUCT
            parent_route: inamika_backoffice_products

inamika_backoffice_products_get:
    path:     /get/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Products:get }
    methods: [GET]
    options:
        breadcrumb:
            label: PRODUCT
            parent_route: inamika_backoffice_products

inamika_backoffice_products_edit:
    path:     /edit/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Products:edit }
    methods: [GET]
    options:
        breadcrumb:
            label: PRODUCTS_EDIT
            parent_route: inamika_backoffice_products

inamika_backoffice_products_delete:
    path:     /delete/{id}
    defaults: { _controller: InamikaBackOfficeBundle:Products:delete }
    methods: [POST,DELETE]