api_customers:
    path:     /customers
    defaults: { _controller: InamikaApiBundle:Customers:index }
    methods: [GET]

api_customers_get:
    path:     /customers/{id}
    defaults: { _controller: InamikaApiBundle:Customers:get }
    methods: [GET]

api_customers_orders:
    path:     /customers/{id}/orders
    defaults: { _controller: InamikaApiBundle:Customers:orders }
    methods: [GET]

api_customers_refreshToken:
    path:     /customers/{id}/refreshToken
    defaults: { _controller: InamikaApiBundle:Customers:refreshToken }
    methods: [PUT]

api_customers_post:
    path:     /customers
    defaults: { _controller: InamikaApiBundle:Customers:post }
    methods: [POST]

api_customers_put:
    path:     /customers/{id}
    defaults: { _controller: InamikaApiBundle:Customers:put }
    methods: [PUT]

api_customers_blankPassword:
    path:     /customersBlankPassword/
    defaults: { _controller: InamikaApiBundle:Customers:blankPassword }
    methods: [PUT]

api_customers_delete:
    path:     /customers/{id}
    defaults: { _controller: InamikaApiBundle:Customers:delete }
    methods: [DELETE]
