api_service_subcategories:
    path:     /service_subcategories
    defaults: { _controller: InamikaApiBundle:ServiceSubcategories:index }
    methods: [GET]

api_service_subcategories_get:
    path:     /service_subcategories/{id}
    defaults: { _controller: InamikaApiBundle:ServiceSubcategories:get }
    methods: [GET]

api_service_subcategories_post:
    path:     /service_subcategories
    defaults: { _controller: InamikaApiBundle:ServiceSubcategories:post }
    methods: [POST]

api_service_subcategories_put:
    path:     /service_subcategories/{id}
    defaults: { _controller: InamikaApiBundle:ServiceSubcategories:put }
    methods: [PUT]

api_service_subcategories_delete:
    path:     /service_subcategories/{id}
    defaults: { _controller: InamikaApiBundle:ServiceSubcategories:delete }
    methods: [DELETE]
